# Generated by Django 4.1.5 on 2023-04-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_member_event_is_active_event_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='terms_accepted',
        ),
    ]
