# Generated by Django 4.2 on 2023-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_date_end_alter_event_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='promo_text',
        ),
        migrations.AddField(
            model_name='booking',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
