runtime: python310

entrypoint: gunicorn -b :$PORT core.wsgi:application

automatic_scaling:
  max_instances: 3

default_expiration: "7d"

env_variables:
  APPENGINE_URL: https://crassula.io
  GS_BUCKET_NAME: crassula-website_crassula
  DJANGO_SETTINGS_MODULE: core.settings.production

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
    secure: always
