version: "3.9"

services:

  db:
    container_name: postgres_crl
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  web:
    container_name: django_crl
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=core.settings.local
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  gcp-creds:


