# Generated by Django 4.1.5 on 2023-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('seo_title', models.CharField(max_length=180, unique=True)),
                ('seo_description', models.TextField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(null=True, upload_to='marketplace/app/logo')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('header', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header (75 characters)')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('seo_title', models.CharField(max_length=180, unique=True)),
                ('seo_description', models.TextField(max_length=300, unique=True)),
                ('small_description', models.TextField(max_length=75, verbose_name='Small description (75 characters)')),
                ('full_description', models.TextField(max_length=1000)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('faq_url', models.URLField(blank=True, null=True)),
                ('show_screens', models.BooleanField(default=False)),
                ('screen_1', models.ImageField(null=True, upload_to='marketplace/app/screen')),
                ('screen_2', models.ImageField(null=True, upload_to='marketplace/app/screen')),
                ('screen_3', models.ImageField(null=True, upload_to='marketplace/app/screen')),
                ('screen_4', models.ImageField(null=True, upload_to='marketplace/app/screen')),
                ('screen_5', models.ImageField(null=True, upload_to='marketplace/app/screen')),
                ('categories', models.ManyToManyField(to='marketplace.category')),
                ('features', models.ManyToManyField(blank=True, null=True, to='features.feature')),
            ],
        ),
    ]
