# Generated by Django 4.1.5 on 2023-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_app_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/logo'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_1',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/screen'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_2',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/screen'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_3',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/screen'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_4',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/screen'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_5',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/screen'),
        ),
    ]
