# Generated by Django 4.1.5 on 2023-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='details_logo',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/app/logo'),
        ),
    ]
