# Generated by Django 4.1.5 on 2023-03-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_app_details_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
