# Generated by Django 4.1.4 on 2022-12-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('seo_title', models.CharField(max_length=200, unique=True)),
                ('seo_description', models.TextField(max_length=300, unique=True)),
                ('date_publish', models.DateTimeField()),
                ('date_edit', models.DateTimeField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'posts',
                'ordering': ['-date_edit'],
            },
        ),
    ]
