# Generated by Django 4.1.4 on 2022-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
