# Generated by Django 4.1.4 on 2022-12-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_edit'], 'verbose_name': 'Post', 'verbose_name_plural': 'posts'},
        ),
    ]
