# Generated by Django 4.2 on 2023-04-26 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_slug_alter_guide_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.TextField()),
                ('sub_content', models.TextField()),
                ('sub_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.guide')),
            ],
            options={
                'verbose_name': 'SubContent',
                'verbose_name_plural': 'SubContent',
                'ordering': ('sub_title',),
            },
        ),
    ]
