# Generated by Django 4.2 on 2023-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_subcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontent',
            name='sub_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='sub_title',
            field=models.TextField(null=True),
        ),
    ]
