# Generated by Django 4.2 on 2023-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_alter_subcontent_sub_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('id',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='subcontent',
            options={'ordering': ('id',), 'verbose_name': 'SubContent', 'verbose_name_plural': 'SubContent'},
        ),
        migrations.AddField(
            model_name='subcontent',
            name='call',
            field=models.BooleanField(default=False),
        ),
    ]
