# Generated by Django 4.2 on 2023-04-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_alter_faq_options_alter_subcontent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='guide',
            new_name='guide_id',
        ),
    ]
