# Generated by Django 4.2 on 2023-04-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_rename_guide_faq_guide_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='slug',
        ),
    ]
